-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Mar 19, 2017 at 10:01 PM
-- Server version: 10.1.13-MariaDB
-- PHP Version: 5.6.23

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `onlinenewsportal`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE `admin` (
  `Id` int(11) NOT NULL,
  `FirstName` varchar(20) NOT NULL,
  `LastName` varchar(20) NOT NULL,
  `Username` varchar(20) NOT NULL,
  `Password` varchar(20) NOT NULL,
  `ConfirmPassword` varchar(20) NOT NULL,
  `PhoneNo` varchar(20) NOT NULL,
  `Email` varchar(50) NOT NULL,
  `Address` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`Id`, `FirstName`, `LastName`, `Username`, `Password`, `ConfirmPassword`, `PhoneNo`, `Email`, `Address`) VALUES
(1, 'kowshik', 'das', 'das_kowshik', '1234567', '1234567', '01670013437', 'das_kowshik@yahoo.com', 'dhaka'),
(7, 'mominul', 'sejan', 'sejanhaque', 'sejanhaque', 'sejanhaque', '01910500346', 'sejan840@gmail.com', 'Dhaka, Bangladesh');

-- --------------------------------------------------------

--
-- Table structure for table `entertainment`
--

CREATE TABLE `entertainment` (
  `Id` int(11) NOT NULL,
  `Post_Title` varchar(200) NOT NULL,
  `Post_Date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Post_Author` varchar(50) NOT NULL,
  `Post_Image` varchar(20) NOT NULL,
  `Post_Content` varchar(2000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `entertainment`
--

INSERT INTO `entertainment` (`Id`, `Post_Title`, `Post_Date`, `Post_Author`, `Post_Image`, `Post_Content`) VALUES
(1, 'Emma Watson private photos stolen in hack', '2017-03-19 20:34:24', 'Prianka Islam', 'emma watson.jpg', 'Beauty and the Beast star Emma Watson is planning to take legal action over photos said to have been leaked online, but her representatives on Wednesday denied reports that the pictures showed the British actor nude. Photos from a clothes fitting Emma had with a stylist a couple of years ago have been stolen. They are not nude photographs.'),
(2, 'Deepika staying connected with her family', '2017-03-19 20:34:24', 'Paramita Saha setu', 'deepika.png', 'Deepika Padukone who is often living out of her bags, makes use of the social networking App to stay connected with her family. \r\nIt is well known that Deepika hails from Bangalore (Karnataka) and lives by herself in Mumbai, but like many others, she has also gotten on to a WhatsApp group to stay in touch with her family. \r\nThe actress stays in touch with her parents, sister Anisha at all times through a whatsapp group. This way, she is always aware of what is happening in her family.'),
(7, 'Cate Blanchett, too Hard to Handle!', '2017-03-19 20:34:24', 'Jubair Ahmed', 'cate.jpg', 'The International Film Festival of Rotterdam showed the European Premiere of â€œManifestoâ€, after the world wide premiere at Sundance Film Festival. The film was produced, directed and written by Julian Rosefeldt. It was largely dominated by Cate Blanchett where she played 13 different roles performing various manifestos. The plot of the film revolves around the various types of artist manifestos of different characters in different time periods. During the premiere of the show, Julian indicated that it was initially a challenge working with Cate as she dominated the entire set. However, as time went by the director could see how she did a tremendous job. There truly is a reason as to why she is one of the most prominent performers of her time. '),
(8, 'An Encounter with the Festival Director', '2017-03-19 20:34:24', 'Prianka Islam', 'fest.jpg', 'IFFR is a festival that tries to bring new and upcoming filmmakers to the front and celebrate the ones that have already enriched us with their works and career. For instance, in this festival we have a Hivos Tiger Award where we celebrate the most daring filmmakers with new visions of cinema and are not afraid of taking on a never-tried-before challenge. Apart from celebrating exceptional movies, we also serve as a launching pad for distribution to a large group of audiences. So, we have both the industry people and the regular audiences coming to watch the films and appreciate them. We wanted to have a huge festival while providing everyone here with a theatre experience. Finally what I am personally very happy for is that in this pivotal year of craziness and politics and the divides within the society, we were able to show films by filmmakers who were able to reflect upon these polarizations. We had Barry Jenkins with â€œMoonlightâ€, who did an excellent job in producing this masterpiece of a movie. We also had many other films that reflect upon the themes that are not alive today but should be discussed through cinema.'),
(9, '"Avatar 2" movie "not happening" in 2018, James Cameron says', '2017-03-19 20:34:24', 'kowshik das', 'avatar_2.jpg', 'The sequel to all-time box office champion "Avatar" has been delayed again and will not be arriving in movie theaters as expected in 2018, director James Cameron has said.\r\n\r\nCameron told the Toronto Star that he was working on all four planned movie sequels simultaneously and had no firm release date for "Avatar 2."\r\n\r\n"Well 2018 is not happening. We have not announced a firm release date," the Oscar-winning director told the newspaper in an interview published on Thursday, when asked about progress on "Avatar 2."\r\n\r\n"What people have to understand is that this is a cadence of releases. So we are not making "Avatar 2." We are making "Avatar 2, 3, 4 and 5. It is an epic undertaking.â€\r\n\r\n"It took us four-and-a-half years to make one movie and now we are making four. We are full tilt boogie right now," Cameron added.\r\n\r\nThe 2009 release of Twentieth Century Fox movie "Avatar," a fantasy adventure set in the distant magical world of Pandora, smashed box office records, taking in an as yet unrivaled $2.8 billion worldwide.'),
(10, 'Dangal', '2017-03-19 20:34:24', 'Jubair Ahmed', 'dangal_3.jpg', 'Director: Nitest Tiwari\r\n\r\nScreenplay: NiteshTiwari , Shreyas Jain\r\n\r\nCast: Aamir Khan, Fatima Sana Sheikh, Sanya Malhotra, Sakshi Tanwar\r\n\r\nStrength: Storyline, acting, cinematography\r\n\r\nWeakness: Length\r\n\r\nRuntime: 152min\r\n\r\nReview: 8/10\r\n\r\nPlot: The movie is about Mahavir Singh Phogat who teaches wrestling to his two daughters with the hope the that they will one day win gold medals and make the country proud.\r\n\r\n\r\n\r\nReview: The movie is directed by Nitest Tiwari. The role of Mahavir Singh Phogat is played by Aamir Khan. His two daughters, Geeta Phogat and Babita Kumari are played by the newcomers, Fatima Sana Sheikh and Sanya Malhotra. Sakshi Tanwar plays the role of Mahavir Singh wife. '),
(11, 'Aynabaji', '2017-03-19 20:34:24', 'M H Sejan', 'aynabaji_4.jpg', 'Director: Amitabh Reza Chowdhury\r\n\r\nWriter: Syed Gaosul Alam Shaon\r\n\r\nStars: Chanchal Chowdhury, Masuma Rahman Nabila, Partho Barua\r\n\r\nStrength:  Cast, Story, Cinematography\r\n\r\nWeakness: Duration\r\n\r\nRuntime: 144min\r\n\r\nRating: 4/5\r\n\r\nPLOT: The story of a struggling actor and his survival in a merciless society where he gets to live his profession in real life after failing his career.\r\n\r\nREVIEW: The film provides the viewers with an empathic view to its characters, which is coupled with brilliant storytelling making the audience wanting more. \r\n\r\nFrom the very first scene to the last, the film was entrancing and incredibly engaging. The main factor that contributed to the audiences to be enticed to the whole of the film was the amazing script that was transformed into a magnetic narration. The directorial debut of famous ad-maker Amitabh Reza could not have been done in a better way. A lot had been expected from Amitabh by the audience and every form of hope was met in this film, clearly marking his ground in the film industry. \r\n\r\nEven though the film was engaging, the duration of the film could make the film tedious for some audience. '),
(12, 'Meet Daniela Vega', '2017-03-19 20:34:24', 'Shibly Sirajee', 'de.jpg', 'With capes and skin tight spandex we have imagined heroes saving the day, fighting all odds in search of justice and finally finding peace. The life of Daniela Vega is no less than a superhero movie for us all. This year Berlinale showcased the fabulous work of Daniela though her film â€œA Fantastic Womanâ€.  Much of the film revolves around the struggle of a transgender woman who fights against all odds to be recognized by the society after the death of her lover. Her acting is commendable throughout the film and was a definite film to look out for at the Berlin International Film Festival 2017. The role demanded a transgender actress and Daniela portrayed the character to the brim. '),
(13, 'Stars to Light the Way', '2017-03-19 20:34:24', 'kowshik das', 'str.jpg', 'It is not strange for us to see a crowd surrounding actors such as Richard Gere. Where presses line up to get an exclusive from the legends and the crowd gathers to get a peek at men of such stature, we simply stop and contemplate the history behind the making of the stars. Do movies make a star or does the star make a movie? Is the fame the real reason why a star is cast? Questions such as this are the first thing that comes to mind while watching films like â€œThe Dinnerâ€. Despite Oren Moverman valiant efforts, the film remains a text-oriented film, which is too heavy for the viewers. It seems the film rose to success in the Berlinale, almost at the expense of the cast fame.'),
(14, 'Reintroducing Rainer Werner Fassbinder', '2017-03-19 20:34:24', 'Saymatul Tuba', 're.jpg', 'If left to an avid movie enthusiast, everyone would have attended the Berlinale if they got to meet the late Rainer Werner Fassbinder. This yearâ€™s Berlinale gave us an all- around access to the directors mind while viewing the retrospective of Fassbinder. The program featured the restored version of Fassbinders working-class TV series â€œEight Hours Do not Make a Dayâ€. The five-part drama is an example of the so-called "worker film". For a short time it enabled filmmakers to address social realities and economic constraints in West Germany. The series main characters represent three generations whose attitudes to life range from progressive to conservative.'),
(15, 'Jaya on Boishakh', '2017-03-19 20:34:24', 'Shariful Islam', 'jaya_ahsan_6.jpg', 'Jaya Ahsan is not just a household name anymore; she is making noise in Calcutta as well. Her films have created waves across Tallywood. Carrying her work, Joya Ahsan has bagged another film named â€œBishorjonâ€ that is set to release this Boishakh, under the direction of Kaushik Ganguly alongside Abir Chatterjee. The film, according to the actress, talks about the social issue where the borders do not separate beings bounded by blood, culture, race and love. The setting of the story is based on the ages of East Pakistan. Previously, Joya Ahsan has acted in â€œAbortoâ€, â€œEkti Bangali Bhut Er Golpoâ€, â€œRajkahiniâ€ and â€œEgoler Chokhâ€. Nowadays Joya is busy with shooting in â€œBeauty Circusâ€ and prepping for â€œDebiâ€.'),
(16, 'No interest in Hollywood?', '2017-03-19 20:34:24', 'M H Sejan', 'aamir_khan_6.jpg', '"Dangal" star, Aamir Khan, expressed his views by saying that Hollywood does not interest him. The actor added, â€œI have a relationship with the audience here for last 25-26 years and I cherish and give a lot of value to it.â€ The 51 year old actor explained that working for Hollywood was never in his career graphs, but it does not mean that he is adamant of not working in international films. In fact, if he finds an interesting film he might consider.\r\n\r\nAfter expressing his lack of interest in Hollywood, he has also explained how it is not necessarily a bad thing. Is Aamir trying too hard not to offend the actors who chose to work for Hollywood?'),
(17, 'Safa Kabir', '2017-03-19 20:34:24', 'Shariful Islam', 'safa_kabir_0.jpg', 'Given Safa Kabir is busy schedule, she does not get a lot of time in the morning to go through a rigorous beauty regime. But since she does need to apply a lot of makeup every day, she tries to keep her skin as clean as possible. Therefore, every night, she dedicates some time to her skin. Her skin routine starts with a cleanser which she massages for a few minutes and then follows that with a scrub. Once her skin is free of all makeup, she applies a moisturizer.\r\n\r\nWhen it comes to hair, she doesnt really get the time to do much, but she makes sure to go the parlor once or twice a month and get a hot oil massage or a keratin treatment. That is the secret to her long, strong and luscious locks. \r\n\r\nAnother secret that Safa Kabir shared with us is that she makes sure that a large part of her diet consists of fruits and juices. She always starts the day with a fruit and usually that is also always her companion on the way to her shoot. She makes sure to drink a lot of water  and eat a lot of vegetables to keep her body clear of all kinds of toxins. Because ultimately what you eat will show on your face. No matter how well you take care of your skin, it will be all for nothing if you are not eating healthy. Therefore, the first step to healthy and beautiful skin and hair is always eating healthy.'),
(18, 'Animation movie Despicable Me 3 to watch out for in 2017', '2017-03-19 20:34:24', 'kowshik das', 'maxresdefault.jpg', 'Animated films are incredibly interesting and entertaining, and this year we absolutely loved watching the likes of Moana, Zootopia, Kung Fu Panda 3, and Secret Life of Pets to name a few amid a whole lot of animated films released in 2016. In fact, a record 27 animated feature films were submitted for consideration for the 89th Academy Awards, virtually making 2016 the greatest year ever for animated movies, until may be next year, which is just round the corner with a lot of prospects ahead of this popular movie genre.\r\n\r\nCheck out the most anticipated animated Hollywood films to be released in 2017, listed here according to their release dates.\r\n\r\nMonster '),
(19, 'Jennifer Lawrence tops list of highest-paid actresses', '2017-03-19 20:36:01', 'kowshik das avro', 'jennifer.jpg-ns.jpg', 'The odds really were in Jennifer Lawrences favor last year as she raked in $52 million, topping a ranking of the highest-paid actresses by a wide margin.\r\n\r\nThe "Hunger Games" star easily surpassed the $35.5 million second-place Scarlett Johansson earned over the past 12 months, according to Forbes magazines annual estimates of the earnings of Hollywood top female stars, released Thursday.\r\n\r\nAll told, four women made more than $20 million from their acting and endorsements, before taxes and fees, while 21 male actors did, underlining a lingering pay gap in Tinseltown.\r\n\r\nForbes pointed to the discrepancy in profit cuts between the male and female -- including Lawrence -- actors in the 2013 film "American Hustle" as an example. The male leads were reported to have taken home a two percent higher cut than the female leads.');

-- --------------------------------------------------------

--
-- Table structure for table `international`
--

CREATE TABLE `international` (
  `Id` int(11) NOT NULL,
  `Post_Title` varchar(200) NOT NULL,
  `Post_Date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Post_Author` varchar(50) NOT NULL,
  `Post_Image` varchar(20) NOT NULL,
  `Post_Content` varchar(2000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `international`
--

INSERT INTO `international` (`Id`, `Post_Title`, `Post_Date`, `Post_Author`, `Post_Image`, `Post_Content`) VALUES
(1, 'Letter bomb injures one in Paris office', '2017-03-19 20:24:58', 'M H Sejan', 'letter bomb.jpg', 'A letter has exploded at the International Monetary Fund in Paris, leaving at least one person injured.\r\nStaff from the office were evacuated and armed police and soldiers descended on the building on Thursday morning.\r\nThe small explosion happened after a person opened an envelope at the IMF office, which is also next door to the World Bank. It is yet unclear who sent the letter but police are currently investigating the scene in the west of the French capital.'),
(2, 'Tillerson calls for new approach to North Korea, but no details', '2017-03-19 20:24:58', 'Saymatul Tuba', 'korea-us.jpg', 'U.S. Secretary of State Rex Tillerson said on Thursday the escalating threat from North Korea nuclear program showed a clear need for a new approach, although he stopped short of detailing what steps the Trump administration would pursue.\r\nTillerson was speaking at a news conference following talks with Japanese Foreign Minister Fumio Kishida in Tokyo, the start of his first trip to Asia as secretary of state.'),
(5, '31 killed in airstrike', '2017-03-19 20:24:58', 'Kabir Ahmed', 'yemen_air_strike.jpg', 'Thirty-one Somali refugees were killed off the coast of Yemen late on Thursday when a helicopter attacked the boat they were travelling in, a local coast guard in the Houthi-controlled Hodeidah area said.\r\n\r\nCoast guard Mohamed al-Alay told Reuters the refugees, carrying official UNHCR documents, were on their way from Yemen to Sudan when they were attacked by an Apache helicopter near the Bab al-Mandeb strait.\r\n\r\nIt was not immediately clear who carried out the attack.\r\n\r\nThe rebel-controlled Saba agency accused the Saudi-led coalition battling the insurgents of attacking the refugees from the air but did not provide further details.\r\n\r\nThe spokesperson for the coalition, General Ahmed al-Asseri, said they did not conduct any operations or have any engagement in the Hodeidah area on Thursday.'),
(6, 'Military action an ', '2017-03-19 20:24:58', 'Jubair Ahmed', 'us.jpg', 'Military action by the United States against nuclear-armed North Korea is an "option on the table" if the threat from the rogue regime escalates, Washingtons top diplomat Rex Tillerson said yesterday.\r\n\r\nThe strong comments from the secretary of state, in Asia for his first foray into crisis management, appear to signal a sea change in American policy towards the isolated country.\r\n\r\nTillersons tour comes after a missile launch last week that Pyongyang described as a drill for an attack on US bases in Japan.\r\n\r\nThe US has 28,000 troops stationed in South Korea to defend it from the North, but the capital Seoul is within range of Pyongyangs artillery and analysts believe any conflict could risk rapid escalation and heavy casualties.\r\n\r\nEven so, Tillerson announced the end of United States "strategic patience" -- the stance of the previous administration under Barack Obama.'),
(7, 'US promises new North Korea plan', '2017-03-19 20:24:58', 'M H Sejan', 'tillerson_1.jpg', 'The United States yesterday vowed a fresh strategy to counter the North Korean nuclear threat, admitting that all previous efforts had failed.\r\n\r\nDuring a visit to Japan at the start of an Asian tour, Secretary of State Rex Tillerson said he would urge China to play its part in reining in its neighbour.\r\n\r\nIn his first foray into crisis diplomacy, the new US envoy wants to reassure key Asian allies that Washington stands with them in the face of the accelerating nuclear and missile threats.\r\n\r\nBut he warned that past policies and punishments have had virtually no effect on Pyongyangs ambitions.\r\n\r\n"I think it is important to recognise that the diplomatic and other efforts of the past 20 years to bring North Korea to a point of denuclearisation have failed," he told a press conference with Japans Foreign Minister Fumio Kishida.\r\n\r\nNorth Korea has a long-standing ambition to become a nuclear power and conducted its first underground atomic test in 2006, in the teeth of global opposition. Four more test blasts have followed, two of them last year.'),
(8, 'India fast-tracks hydropower projects in disputed Kashmir', '2017-03-19 20:24:58', 'Prianka Islam', 'kashmir_power.jpg', 'India has fast-tracked hydropower projects worth $15 billion in Kashmir in recent months, three federal and state officials said, ignoring warnings from Islamabad that power stations on rivers flowing into Pakistan will disrupt water supplies.\r\n\r\nThe swift approval of projects that had languished for years came after Prime Minister Narendra Modi suggested last year that sharing the waterways could be conditional on Pakistan clamping down on anti-India militants that New Delhi says it shelters.\r\n\r\nPakistan has opposed some of these projects before, saying they violate a World Bank-mediated treaty on the sharing of the Indus river and its tributaries upon which 80 percent of its irrigated agriculture depends.\r\n\r\nThe schemes, the largest of which is the 1,856 MW Sawalkote plant, will take years to complete, but their approval could prove a flashpoint between the nuclear-armed neighbours at a time when relations are at a low ebb.'),
(9, 'Trump, Saudi Arabia in mutual embrace', '2017-03-19 20:24:58', 'Tahrima Humayra', 'trump_prince.jpg', 'US President Donald Trump may not be popular in much of the Muslim world but he has been embraced by Saudi Arabia and, in turn, has reached out to the oil-rich kingdom.\r\n\r\nA meeting Tuesday in Washington between Trump and the powerful Saudi Deputy Crown Prince, Mohammed bin Salman, confirmed that the new government in Washington sees Riyadh as a critical partner for both security and investment, analysts say.\r\n\r\nPrince Mohammed, 31, whose country is the birthplace of Islam, was one of the first foreign leaders to visit Trump, who has vowed to fight "radical Islamic terrorism".\r\n\r\nHis trip followed a series of laudatory comments towards the new administration from Saudi Arabia, whose relations were increasingly frayed under former president Barack Obama.'),
(10, 'Holy wars will soon begin in Europe', '2017-03-19 20:24:58', 'Shariful Islam', 'cavusoglu_0.jpg', 'A Turkish minister has claimed "holy wars will soon begin" in Europe, in spite of the defeat of far-right leader Geert Wilders in the Netherlands elections.\r\n\r\nMevlut Cavusoglu, Turkeys foreign minister, did not welcome the victory for Prime Minister Mark Ruttes centre-right Peoples Party for Freedom and Democracy (VVD).\r\n\r\nâ€œNow the election is over in the Netherlands...when you look at the many parties you see there is no difference between the social democrats and fascist Wilders,â€ he said according to a translation by Hurriyet.\r\n\r\nâ€œAll have the same mentality. Where will you go? Where are you taking Europe? You have begun to collapse Europe. You are dragging Europe into the abyss. Holy wars will soon begin in Europe.â€\r\n\r\nWilders attempted to capitalise on an ongoing diplomatic row between the Netherlands and Turkey during his election campaign, leading a small protest outside the countrys embassy and calling Erdogan a â€œdictatorâ€.'),
(11, 'Trump slashes foreign aid', '2017-03-19 20:24:58', 'Shibly Sirajee', 'trump_132.jpg', 'President Donald Trump proposed drastic cuts in spending on the arts, science, foreign aid and environmental protection yesterday, in a security-focused budget blueprint that could struggle to pass Congress.\r\n\r\nTranslating hardline campaign promises into dollar-and-cent commitments, the Republican leader proposed scrapping dozens of programs like public broadcasting and climate funding, while boosting Pentagon spending by $52 billion.\r\n\r\nTrump, in the preface to the spending proposal, described it as "a budget that puts America first," and that makes safety and security the "number one priority -- because without safety, there can be no prosperity."\r\n\r\nThe State Department and the Environmental Protection Agency would be the biggest losers, seeing their funding reduced by around a third.\r\n\r\nThat could be a harbinger of steep reductions in foreign aid and funding to UN agencies, with knock-on effects around the world.'),
(12, 'Ankara threatens to send "15,000 refugees a month"', '2017-03-19 20:24:58', 'Ramzan Hussain', 'merkel_15.jpg', 'Turkey Interior Minister Suleyman Soylu has threatened to "blow the mind" of Europe by sending 15,000 refugees a month to EU territory, in an intensifying dispute with the bloc.\r\n\r\nAnkara and Brussels almost a year ago on March 18 signed a landmark deal that has substantially lessened the flow of migrants from Turkey to Europe.\r\n\r\nBut the accord is now hanging in the balance due to the diplomatic crisis over the blocking of Turkish ministers from holding rallies in Europe.\r\n\r\n"If you want, we could open the way for 15,000 refugees that we do not send each month and blow the mind" of Europe, Soylu said in a speech late Thursday, quoted by the Anadolu news agency.\r\n\r\nForeign Minister Mevlut Cavusoglu has already indicated that Turkey could rip up the deal and said Turkey was no longer readmitting migrants who crossed into Greece.'),
(13, 'Syria-Israel tensions flare', '2017-03-19 20:24:58', 'Saymatul Tuba', 'syria_war_17.jpg', 'Israeli warplanes struck several targets in Syria early yesterday, prompting retaliatory missile launches, in the most serious incident between the two countries since the Syrian civil war began six years ago.\r\n\r\nSyria military said it had downed an Israeli plane and hit another as they were carrying out pre-dawn strikes near the famed desert city of Palmyra that it recaptured from jihadists this month.\r\n\r\nThe Israeli military denied that any planes had been struck. The Syrian government has made similar unfounded claims in the past.\r\n\r\nNevertheless, analysts said the incident represented a significant shift in Syria response to Israeli airstrikes inside its territory.\r\n\r\nThe air force said earlier that it had carried out several strikes on Syria overnight, but that none of the ground-to-air missiles fired by Syrian forces in response had hit Israeli aircraft.\r\n\r\nIt was an unusual confirmation by the Jewish state of air raids inside Syria.\r\n\r\nIn April 2016, Prime Minister Benjamin Netanyahu admitted for the first time that Israel had attacked dozens of convoys transporting weapons in Syria destined for Lebanons Hezbollah, which fought a devastating 2006 war with Israel and is now fighting alongside the Damascus regime.\r\n\r\n'),
(14, 'Trump welcomes Merkel in White House after delay', '2017-03-19 20:24:58', 'Shibly Sirajee', 'trump_merkel.jpg', 'US President Donald Trump yesterday welcomed German Chancellor Angela Merkel to the White House for talks expected to focus on their differences over Nato, Russia, global trade and a host of other issues.\r\n\r\nThe two leaders shook hands and smiled for the cameras before entering the West Wing.\r\n\r\nTalks had been scheduled for Tuesday, before a blizzard in the eastern United States forced a postponement.\r\n\r\nFor years, Merkel -- a trained physicist -- had been president Barack Obama closest international partner, with the two sharing a strong rapport and a similar deliberative approach.\r\n\r\nWith Trump, Merkel may settle for avoiding an open argument or a 140-character Twitter missive.\r\n\r\nBefore coming to office the US president called Merkels acceptance of refugees a "catastrophic mistake" and said she was "ruining Germany."\r\n\r\nHe also demanded countries like Germany step up defense spending, a sensitive issue for a nation that has had a strong pacifist tradition since World War II and proselytizes fiscal prudence.\r\n\r\nIn a similar vein, Merkel has sought to remind the real estate mogul of democratic values.'),
(15, 'China, Pakistan to jointly build missiles, aircraft', '2017-03-19 20:24:58', 'Anindya Poddar', 'china_pakistan.jpg', 'Beijing was furious with India last year for launching Agni V, but now it plans to build ballistic, cruise, anti-aircraft and anti-ship missiles with "all-weather friend" Pakistan, Chinas state-run media reported.\r\n\r\nThe two countries will also jointly mass produce FC-1 Xiaolong, a lightweight and multi-role combat aircraft, reported Global Times, the Chinese Communist Parties news outlet.\r\n\r\nIn addition, the two agreed to strengthen anti-terrorism cooperation and strike terrorist forces including Chinas insurgent East Turkestan Islamic Movement.\r\n\r\nThese were the outcomes of yesterdays meeting in Beijing between Pakistans army chief Qamar Bajwa and a top Chinese military official, Fang Fenghui. In exchange for Beijings largesse, Islamabad agreed to ensure the safety of the China-Pakistan Economic Corridor (CPEC).\r\n\r\n"Pakistan and China enjoy a special friendly relationship with each other and have a common destiny," Bajwa reportedly said at the meeting, according to a statement on the website of Chinas defence ministry.'),
(16, 'Fall of the Queen', '2017-03-19 20:24:58', 'Tanzin Mim', 'park_reuters.jpg', 'In the summer of 1974, Park Geun Hye was 22 and studying at the University of Grenoble in France. Her ambition was to become a teacher.\r\n\r\nOne balmy day in August, that dream was shattered forever. She received a message from her native South Korea: Come back immediately.\r\n\r\nShe packed her bags and rushed to the airport. As she hurried past a newsstand, a headline caught her eye and she froze.\r\n\r\n"First Lady Madam Park Assassinated," it read. Above it was a photo of a fair-skinned woman with kindly eyes and gentle smile-- her mother.\r\n\r\nThe young woman felt as if a knife had been plunged into her heart.\r\n\r\nBack in Seoul, Park was given the blood-stained dress her mother was wearing at the time of her killing on August 15, 1974.'),
(17, 'China, Saudi Arabia consider deals worth about $65bn', '2017-03-19 20:30:59', 'Jubair Ahmed Likhon', 'china-saudi-web.jpg', 'China and Saudi Arabia on Thursday signed memorandums of understanding and letters of intent potentially worth about $65 billion during Saudi King Salmans visit to Beijing, a senior Chinese diplomat said.\r\n\r\nDeputy Chinese Foreign Minister Zhang Ming said the agreements involved investment, energy, space and other areas, but did not give details.\r\n\r\nThe octogenarian monarch, who has overseen the launch of an ambitious economic reform plan since his accession two years ago, is on a month-long Asian tour. The visits to countries that are some of worlds fastest growing importers of Saudi oil aim to promote investment opportunities in the kingdom, including the sale of a stake in its giant state firm Saudi Aramco.\r\n\r\nSaudi Arabia has sought to boost oil sales to China, the worlds second-largest oil market, after losing market share to Russia last year, by working mostly with Chinas top three state oil firms.');

-- --------------------------------------------------------

--
-- Table structure for table `national`
--

CREATE TABLE `national` (
  `Id` int(11) NOT NULL,
  `Post_Title` varchar(200) NOT NULL,
  `Post_Date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Post_Author` varchar(50) NOT NULL,
  `Post_Image` varchar(50) NOT NULL,
  `Post_Content` varchar(2000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `national`
--

INSERT INTO `national` (`Id`, `Post_Title`, `Post_Date`, `Post_Author`, `Post_Image`, `Post_Content`) VALUES
(1, 'Vested group set fire on Shanties of Korail slum', '2017-03-19 20:09:52', 'kowshik das', 'vested.jpg', 'A vested group of people allegedly set fire on the Shanties of Korail slum in the citys Mohakhali area on Thursday to grab around 150 acres of land by evicting hundreds of residents of the area, source said.\r\n\r\nAccording to official record, this is the fourth time fire set by the vested group.\r\n\r\nResidents of the slum claimed that a number of high profile personalities backed by some local ruling men trying to evict the rootless people to occupy the lands of the countrys largest slum. \r\n\r\nThey are using several gangs of miscreants to set fire in the shanties that already has been created a deep panic among the victims as well as countrymen, they added. \r\n\r\nAccording to them, residents of the slum have been gripped in fear of eviction since that Bangladesh Telecommunication Company Ltd (BTCL) has taken a plan to recover the land to set up a high-tech park under the Private Sector Development Support Project in the 19-hectare land of the slum. The World Bank and the Department for International Development (DFID) are funding the high-tech park project.'),
(2, 'Suicide blast kills bomber at Ashkona RAB camp', '2017-03-19 20:09:52', 'M H Sejan', 'suicide.jpg', 'A suspected bomber died in what is believed to be a suicide blast at a barrack of the Rapid Action Battalion (RAB) in Dhaka Ashkona area during Jumma prayers on Friday.\r\n\r\nThe bomber died on the spot wounding two RAB men who were being treated at the nearby Combined Military Hospital (CMH) in Dhaka Cantonment, Mufti Mahmud Khan, Director of the Force Legal and Media Wing, told journalists.\r\n\r\nKhan said the attack appeared to be an act of any militant outfit but it was not clear immediately which of the Islamist outfits staged it.\r\n\r\n"Right now we are, however, concentrating our attention to ascertain if the complex and the neighbourhood are secured," he said as polices counter terrorism unit with bomb disposal team reached the scene while thoroughfares around the complex were blocked for vehicular movements.'),
(3, 'RAB will not take responsibility of crime committed by its members', '2017-03-19 20:09:52', 'Jubair Ahmed', 'rab_5.jpg', 'The Director General of the Rapid Action Battalion (RAB) Benazir Ahmed said the elite force would not take the responsibility for criminal activities committed by its members and will never compromise with their unprofessional acts. \r\nThe DG came up with the comment while addressing as the chief guest in a two-day annual Commanding Officers (COs) conference at RAB Headquarters in the city.\r\nThe conference ended on Wednesday afternoon.\r\nReferring to the Naryanganj incident, the RAB DG also issued warnings against any sort of criminal activities by its personnel in future.The elite force chief said, "Of course this is a message for unscrupulous RAB personnel that no one will be spared. Anybody who commits crime will be punished. No one is above the law."\r\nHe criticized some RAB officials involvement in the murder of seven persons in Narayanganj that tarnished the forces image.\r\nThe DG alerted the elite force personnel and gave necessary instruction to them so that nobody will have to involve in such crime further.'),
(4, 'Khilgaon attacker body bears 6 injury marks: Doctors', '2017-03-19 20:09:52', 'Prianka Islam', 'khilga.jpg', 'Doctors found six marks of "bullet wounds" in the body of the unidentified miscreant who was shot dead during his attempt to intrude into a Rab checkpost in the city Khilgaon area early Saturday.\r\nTalking to reporters on completion of the autopsy on the body of the alleged attacker at Dhaka Medical College Hospital (DMCH) morgue in the afternoon, Dr Sohel Mahmud, the chief of the Department of Forensic Medicine (DFM) \r\nof the hospital, said the miscreant was killed by bullets the marks of which were found in his body.\r\nThe doctors collected blood, hair and flesh from the body during the autopsy for DNA and pathological tests, Dr Sohel said. Sub-inspector of Khilgaon police station Emadul Haque, who took the body to the DMCH morgue, told reporters that in the postmortem report it was mentioned that two bullet marks were found in the left shoulder while two on its left side of the chest, one on right side of the chest and one in the right foot.\r\nEarlier, the autopsy of the alleged militant, who was killed following the blast of bombs carried by him at a barrack of Rapid Action Battalion (RAB) at Ashkona in the city on Friday, was completed at the DMCH on Saturday.'),
(5, 'Two killed in Tangail road accident', '2017-03-19 20:09:52', 'Saymatul Tuba', 'accident.jpg', 'UNB, Tangail :Two people were killed and three others injured when a truck rammed a CNG-run auto-rickshaw at Rasulpur in Sadar upazila on Friday.The accident took place around 6:30 am when a Mymensingh-bound truck from Tangail hit a CNG-run auto-rickshaw coming from the opposite direction, leaving two passengers of the auto-rickshaw killed on the spot and three others injured, said Sun-inspector Jahangir Alam, in-charge of Elenga highway police camp.The injured were rushed to Tangail Medical College Hospital. Police could not arrest the truck driver as he managed to flee the scene.'),
(6, 'Attack on UK Envoy: No bar to execute Huji chief Hannan', '2017-03-19 20:09:52', 'Shariful Islam', 'hannan-wb.jpg', 'No legal obstacle remain for the execution of the death sentence of three Harkat-ul-Jihad al-Islami (Huji) militants including its chief Mufti Abdul Hannan in a case filed for grenade attack on the then UK envoy in Bangladesh in 2004.\r\n\r\nThe Supreme Court today dismissed a petition filed by Mufti Hannan seeking review of its verdict that upheld a High Court judgement awarding death penalty to three militants including Hannan in the case.\r\nThe Supreme Court on Sunday, March 19, 2017, dismisses a petition filed by banned militant outfit Harkat-ul-Jihad Bangladesh (Huji) chief Mufti Hannan seeking review of its verdict that upheld a High Court judgement awarding death penalty to the three in the case. '),
(7, 'Dhaka College students block Mirpur road', '2017-03-19 20:09:52', 'Ramzan Hussain', 'dhaka-college.jpg', 'Vehicular movement on Mirpur Road in Dhaka remained suspended for an hour as Dhaka College students blocked the road in front of their institute demanding the college to be turned into a university.\r\n\r\nSeveral hundred of students gathered in front of their college main gate around 11:00am and took to the street, Atiqur Rahman, officer-in-charge of New Market Police Station, told The Daily Star. \r\n\r\nTransport movement became normal after the students left the scene around noon.\r\nVehicular movement on Mirpur Road in Dhaka remained suspended for an hour as Dhaka College students blocked Mirpur road in front of their institute on Sunday, March 19, 2017. The Google Street View shows Dhaka College entrance on Mirpur road in the capital.'),
(8, 'End trial of Ekramul killing case in 6 months: SC', '2017-03-19 20:09:52', 'Shibly Sirajee', 'feni-murder_0.jpg', 'The Supreme Court yesterday stayed a High Court verdict, which granted bail to Mahtab Uddin Chowdhury Minar, the prime accused in Fulgazi upazila chairman Ekramul Haque killing case, till December 4.\r\n\r\nFollowing a government petition moved by Additional Attorney General Murad Reza, Chamber judge of the Appellate Division Justice Syed Mahmud Hossain also sent the stay petition to the full bench of the apex court for its hearing on December 4.\r\n\r\nEkram, 45, also the president of Awami League upazila unit, was shot and burnt to death in his car in Feni town Academy area on May 20, 2014.\r\n\r\nRezaul Haque Jasim, victim brother, filed the murder case with Feni Model Police Station the same day, accusing Mahtab and 30 to 35 anonymous people.\r\n\r\nThe HC on November 24 granted permanent bail to the BNP leader.'),
(9, 'National consensus must to curb militancy: Fakhrul', '2017-03-19 20:09:52', 'Jubair Ahmed', 'fakhrul-wb_1_1.jpg', 'National consensus is a must to combat militancy, BNP Secretary General Mirza Fakhrul Islam Alamgir said today.\r\n\r\nâ€œIt (militancy) is a new phenomenon which the country is facing at present. To eliminate it from the country, national consensus is a must,â€ Fakhrul said while talking to reporters in Thakurgaon bus stand.\r\nThe government should forge unity to combat this, Fakhrul said adding that it is not possible for the government alone to eliminate militancy from the nation.\r\n\r\nâ€œWe hope the government will take measures to create unity among the political parties in this regard,â€ he added.'),
(10, 'Suicide blast at Rab barrack', '2017-03-19 20:09:52', 'Mashuk Kawsar', 'militants_attack_on_rab.jpg', 'A suspected suicide bomber sneaked into a Rab barrack and blew himself up in the capitals Ashkona yesterday, in what appears to be the countrys first such attack by a terror suspect inside a law enforcement agencys compound. \r\n\r\nTerror group Islamic State claimed credit for the attack, reports BBC Bangla. \r\n\r\nThe attacker, who is yet to be identified, died instantly while two Rab members suffered splinter injuries. \r\n\r\n\r\nAll prisons across the country have been put on alert while security has been stepped up at all domestic and international airports and Rab offices following the attack.\r\n\r\nHours after the incident that happened around 1:00pm, At-Tamkin, a pro-Islamic State Bangla blog, said in a post that the attack â€œwas carried out by an explosive beltâ€.'),
(11, 'Uphold Bangabandhu ideals', '2017-03-19 20:09:52', 'FI Amin', 'mausoleum_of_bangabandhu_sheikh_mujibur_rahman.jpg', 'Prime Minister Sheikh Hasina yesterday urged children to uphold the Father of the Nations ideals with a view to becoming future leaders of the country.\r\n\r\n"Now the Father of the Nation is not amongst us, but we must complete the unfinished tasks of Bangabandhu. We have to turn Bangladesh into a prosperous and developed country," she said.\r\n\r\nThe Prime Minister was addressing a childrens rally and cultural programme held at Bangabandhu Mausoleum Complex marking 97th birth anniversary of Bangabandhu and National Childrens Day. The Ministry of Women and Children Affairs and the district administration jointly organised the programme.'),
(12, 'Five hurt in AL factional clash in Gaibandha', '2017-03-19 20:09:52', 'Hussain Zamee', 'awami_league_clash_gaibandha.jpg', 'Five people were injured in a factional clash of Awami League at Saghata upazila in Gaibandha yesterday during a discussion on the 97th birth anniversary of Bangabandhu.\r\n\r\nDeputy Speaker Fazle Rabbi Miah was addressing as chief guest at the discussion held by the upazila administration when the clash with sticks started.\r\n\r\nAccording to witnesses, supporters of Mahmud Hasan Ripon, assistant secretary of a sub-committee of Al central committee, who lost to the deputy speaker in winning nomination for the constituency Gaibandha- 5, were going to place wreath on a mural of Bangabandhu Sheikh Mujibur Rahman where some activists hurled some brick chips at them which later turned into a clash.'),
(13, 'Duta concerned over recent incidents at halls', '2017-03-19 20:09:52', 'Asad Khan', 'du_logo.jpg', 'Dhaka University Teachersâ€™ Association (Duta) today expressed deep concern over the recent incidents at the university dormitories.\r\n\r\nâ€œWe noticed students, teachers and journalists were harassed by some unruly students recently,â€ Duta said in a press release signed by its President Prof Dr ASM Maksud Kamal and General Secretary Prof Dr Md Rahamat Ullah.\r\n\r\nBesides, a tense situation is prevailing at the residential halls centring seat allotment, it also said urging the university students and other concerned people to keep congenial atmosphere on the campus.\r\n\r\nEarlier on Thursday, Bangladesh Chhatra League (BCL) leaders at Ruqayyah Hall tried to occupy some rooms, creating a tense situation at the dorm.'),
(14, 'Woman attacked by stalker', '2017-03-19 20:09:52', 'Kabir Ahmed', 'woman_attacked_by_stalker.jpg', 'Yet another woman has been brutally attacked by a stalker, this time in Patiya upazila in Chittagong. The victim is Misfa Sultana, a school teacher, who apparently provoked the ire of the attacker, Ahasan Ullah Tutul, because she rejected his romantic proposal. Earlier this week, Ahasan stormed into the classroom where Misfa was teaching and beat her so badly that both her hands and left leg were broken.\r\n\r\nWhere do we even begin? This is the tragic reality that girls and women in this country who dare have a say in their lives have to endure. Countless such women are subjected to harassment and physical violence at the hands of men like Ahasan who do not understand the concept of consent. On a daily basis, women have to pay the price of such sexist, chauvinistic attitudes â€“ sometimes with their lives. '),
(15, 'Not only Ctg, 3 nearby dists have ', '2017-03-19 20:29:32', 'kowshik das avro', 'similar_attack_jmb.jpg', 'Counterterrorism officials suspect that â€œNeo JMBâ€ militants have built their hideouts in Coxs Bazar, Bandarban and Rangamati districts apart from Chittagong.\r\n\r\nâ€œThe militants have set up dens in those areas as it would help their safe movement through the sea. A plan to recruit Rohingyas could be another reason,â€ an official of the Counter Terrorism and Transnational Crime (CTTC) unit of the DMP told The Daily Star yesterday.\r\n\r\nThe official said he came to know this after quizzing Ahmed Azwad Imtiaz Talukder alias Omi, a â€œNeo JMBâ€ leader in decision-making position of the outfit.\r\n\r\nThe capital has become very unsafe for the militants as many of their members were arrested and killed in pre-emptive operations by law enforcers, he added.\r\n\r\nAnother CTTC official, who also interrogated Omi, said the suspected militant told them that there are three dens of the terror group in Chittagong.');

-- --------------------------------------------------------

--
-- Table structure for table `sports`
--

CREATE TABLE `sports` (
  `Id` int(11) NOT NULL,
  `Post_Title` varchar(200) NOT NULL,
  `Post_Date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Post_Author` varchar(50) NOT NULL,
  `Post_Image` varchar(20) NOT NULL,
  `Post_Content` varchar(2000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `sports`
--

INSERT INTO `sports` (`Id`, `Post_Title`, `Post_Date`, `Post_Author`, `Post_Image`, `Post_Content`) VALUES
(1, 'Shakib 116 gives Bangladesh control', '2017-03-20 02:33:19', 'Jubair Ahmed Likhon', 'sakib100.jpg', 'Bangladesh made a memorable comeback in their 100th Test as their last five wickets nearly batted through the entire day. Shakib Al Hasan was at the centre of it all, making his fifth century in the format and ensuring his team took the first-innings lead for only the second time while batting second away from home.'),
(2, 'Barcelona draw Juventus, Real Madrid face Bayern in Champions League quarter-final draw', '2017-03-20 02:12:23', 'Tahrima Humayra', 'cl-qf-draw.jpg', 'The two Spanish giants have been given tough tests, while Leicester City face Atletico Madrid and Borussia Dortmund take on Ligue 1 side Monaco\r\n\r\nReigning champions Real Madrid will face Bayern Munich while Barcelona have drawn Juventus in the Champions League quarter-final draw.\r\n\r\nHaunted Wenger running into the last man he wants to face'),
(6, 'Iniesta rejects â‚¬35m offer from China', '2017-03-20 02:12:23', 'Shariful Islam', 'iniesta-bcn.jpg', 'Barcelona captain Andres Iniesta has turned down two offers from China, including one which offered a payment of 35 million euros per year after taxes, reports AS.\r\n\r\nAn unnamed Chinese Super League team is believed to have offered the Spaniard a whopping 35 million euros after taxes per year and also included other benefits such as the option to skip away games.\r\n\r\nIniesta has been engaged in contract negotiations with his contract due to expire in 2018, but he has refused the clubs first offer.\r\n\r\nClub president Josep Maria Bartomeu has suggested a deal of two more years for Iniesta, who will be 33 in May, but the deal was below-par from Iniestas standpoint. Another concern for Iniesta so far has been the lack of playtime and he is concerned with his influence waning in the squad, especially ahead of the 2018 World Cup in Russia.\r\n\r\n â€œI would like to take this opportunity to say, be it one thing or another, Iniesta and Barcelona will never have any kind of problem,â€ he said on Thursday, adding cryptically that â€œthis has been a different year.â€'),
(7, 'Hales, Root tons take England to record ODI win over Windies', '2017-03-20 02:12:23', 'Jubair Ahmed', 'root_10.jpg', 'England Alex Hales and Joe Root struck centuries as the tourists cruised to a series sweep with a massive 186-run victory over West Indies in the third and final one-day international at the Kensington Oval on Thursday.\r\n\r\nEngland, sent in to bat, amassed 328 all out in exactly 50 overs before restricting the hosts to 142 in 39.2 overs for their biggest ever win by runs over the Caribbean side.\r\n\r\nOpener Hales (110 from 107 balls), who returned to the team in place of Sam Billings after recovering from a broken hand, and Root (101 from 108 balls) put on 192 for the second wicket on an uneven pitch, a record for England against West Indies.\r\n\r\nThat laid the platform for the visiting side huge total, but they needed some power-hitting from Ben Stokes (34 from 20 balls) to ensure they made it past 300.\r\n\r\nSeamer Alzarri Joseph, 20, playing in just his third ODI, was the pick of the home bowlers with 4-76, including the wickets of Hayles and Root plus Moeen Ali for a first ball duck.'),
(8, 'Mashrafe signs for Rupganj', '2017-03-20 02:12:23', 'M H Sejan', 'mortaza.jpg', 'Mashrafe Bin Mortaza hogged the spotlight on the opening day of the two-day players transfer for the Dhaka Premier Division Cricket League at the Sher-e-Bangla National Stadium in Mirpur yesterday.\r\n\r\nThe Bangladesh limited-overs captain, who will fly for Colombo today to lead the Tigers in the three-match ODI and two-match T20I series against Sri Lanka, signed for Legends of Rupganj at almost the last second of the bourse after he had mistakenly gone to the Bangabandhu National Stadium -- where the event had been taking place for a long time before shifting to the home of cricket in Mirpur this season.\r\n\r\nMashrafe was excited that the transfer system returned to its traditional form after the player-by-choice system was used in last two seasons.'),
(9, 'Ronaldo expecting twins?', '2017-03-20 02:12:23', 'Shibly Sirajee', 'cr7_3.jpg', 'Football superstar Cristiano Ronaldo is about to become the father of twin boys, The Sun quoted a "family source" as saying.\r\n\r\nA surrogate mother based in the United States of America is in the final weeks of her pregnancy and is said to be expecting babies "very soon".\r\n\r\nThe 32-year-old Real Madrid forward has told his inner circle that the twins will be flown to his mansion on the outskirts of Madrid.\r\n\r\n"Cristiano and his family cannot wait to meet the new members of their clan," The Sun quoted the source as saying. \r\n\r\n"He likes to keep a tight lid on his private life but has told loved ones and close friends the baby boys are due to arrive very soon."\r\n'),
(10, 'India fightback after Smith epic knock', '2017-03-20 02:12:23', 'kowshik das', 'maxwell_2.jpg', 'All-rounder Glenn Maxwell hailed his "awesome" skipper Steve Smith after the duo 191-run partnership helped Australia post a formidable first innings total against India in the third Test in Ranchi Friday.\r\n\r\nMaxwell, returning to the five-day side after nearly three years in the wilderness, cracked his maiden Test century on day two but it was Smith unbeaten 178 that was the bedrock of the tourists 451.\r\n\r\nOpener Lokesh Rahul led India strong reply in the final session with the hosts ending the day on 120 for one. India still trail the visitors by 331 runs.\r\n\r\nMurali Vijay (42) and Cheteshwar Pujara (10) were batting at the break after Rahul was out caught behind for 67 off fast bowler Pat Cummins.\r\n\r\nRahul, who hit 9 fours in his 102-ball stay, registered his fourth fifty of the series to put on 91 runs with opening partner Vijay.\r\n\r\nBut it was the epic partnership between Smith and Maxwell that steered Australia to the highest total of the series so far after the visitors resumed the day on 299-4.'),
(11, 'PERFORMER OF THE DAY: SHAKIB AL HASAN', '2017-03-20 02:12:23', 'Ramzan Hussain', 'shakib1.jpg', 'What difference a day can make on a cricketer mindset and on the complexion of a whole game! On Thursday, Shakib Al Hasan, Bangladesh most illustrious cricketer, looked like a man at odds with everyone. He ruffled feathers of the opposition, looked extremely peeved while sitting at the dressing room and played every shot in anger while at the crease. Extremely lucky to have survived a madcap first eight deliveries, the all-rounder walked half-way towards the dressing room without even waiting for his partner. Yesterday, however, Shakib turned up a completely different man, mindful of his responsibilities as a senior statesman. He batted with extreme caution, in the process notching up his fifth Test century and more importantly guiding the team towards a healthy first-innings lead.'),
(12, 'Champions Trophy arrives', '2017-03-20 02:12:23', 'Paramita Saha', 'trophy_1.jpg', 'The official ICC Champions Trophy 2017, which is travelling to all eight participating nations will arrive in Dhaka today, a press release from the Bangladesh Cricket Board informed.\r\n\r\nThe 3.1 kg trophy will be on put on display at the Centre Court of the Jamuna Future Park from 11:00AM to 09:00PM today and tomorrow.\r\n\r\nOn March 20, the trophy will be taken to an iconic location in Dhaka for a photo shoot which will be followed by a visit to the Sher-e-Bangla National Cricket Stadium in Mirpur.'),
(13, 'Ramos takes Real two clear at top', '2017-03-20 02:12:23', 'Anindya Poddar', 'ramos_7.jpg', 'Real Madrid captain Sergio Ramos struck another late winner as the European champions usurped Barcelona at the top of La Liga with a hard-fought 2-1 win over Real Betis on Sunday.\r\n\r\nEarlier, Barca boss Luis Enrique accepted his side had struggled to shrug off the euphoria of a remarkable Champions League comeback against Paris Saint-Germain as the Spanish champions slumped to a shock 2-1 defeat at Deportivo la Coruna.\r\n\r\nVictory for Madrid moves Real two points clear of Barcelona and with a game in hand still to come.\r\n\r\nHowever, Madrid win was mired in controversy as goalkeeper Keylor Navas was extremely lucky to avoid an early red card before making a brilliant stoppage time save to deny Antonio Sanabria.'),
(14, 'A batsman cut out for Test cricket', '2017-03-20 02:12:23', 'Shibly Sirajee', 'mosaddek_8.jpg', 'Shakib Al Hasan may have grabbed all the headlines yesterday, but there was a debutant without whom Bangladesh would probably not have been able to accumulate the 129-run lead that placed the visitors ahead in the match.\r\n\r\nWhen Mushfiqur Rahim was dismissed for a well-played 52, Bangladesh were six down for 290 and still 48 runs adrift of Sri Lanka first innings score of 338. Things could easily have gone south from there, given Bangladesh penchant for collapses.\r\n\r\nBut unlike many who had walked onto the field in the Bangladesh helmet for the first time in Test cricket, Mosaddek Hossain came with serious first-class pedigree. Although he has played just 21 matches for Dhaka Division in the National Cricket League and East Zone in the Bangladesh Cricket League, he has scored seven centuries and five of them each -- 282, 250, 200 not out, 153 and 152 -- have been big ones, hinting at a propensity to bat long that has given him an average of 68.87 in 33 innings.\r\n\r\nThat facility for longer-version batting was evident during his innings of 75 off 155 balls with seven fours and two sixes. Apart from a few plays and misses off pacer Suranga Lakmal early on, he appeared completely untroubled. Unlike Shakib, Mosaddek did not offer any chances as he first put on 131 with Shakib -- a record for the seventh wicket for Bangladesh against Sri Lanka -- and then 33 for the eighth wicket with Mehedi Hasan Miraz which took Bangladesh lead past 100.'),
(15, 'Neymar out of Deportivo trip after PSG heroics', '2017-03-20 02:12:23', 'Tahrima Humayra', 'neymar-2.jpg', 'Barcelona forward Neymar will miss Sunday La Liga game at Deportivo La Coruna with a thigh problem, the club said on Saturday, depriving the champions of the hero of their stunning 6-1 midweek Champions League win over Paris St Germain.\r\n\r\nThe Brazilian, who scored two of Barca three late goals to complete a historic comeback from a 4-0 first-leg loss to the French champions, missed training on Saturday along with compatriot Rafinha who was suffering from gastroenteritis and has also been left out of the squad for Sunday game.\r\n\r\nBarca lead Real Madrid by a point at the top of the table while their arch-rivals have a game in hand and host struggling Real Betis hours after Barca visit Deportivo, who are unbeaten in their three games under new coach Pepe Mel.\r\n\r\nBarca manager Luis Enrique admitted his side faced a challenge in coming down from the cloud of emotion over their exploits on Wednesday but said he trusted his players to prepare appropriately for the game at Deportivo.\r\n\r\n"Without doubt it is something we have to be aware of and overcome but I trust the wisdom and sense of my players to realise that we are in the final stretch of the season and that we have everything to play for," Luis Enrique told reporters.'),
(16, 'Shakib puts Tigers on top', '2017-03-20 02:12:23', 'Prianka Islam', 'shakib_mosad.jpg', 'Call it resiliency or a perverse desire to prove naysayers wrong, but Bangladesh have made it a habit of turning in a stellar performance when their fans or critics least expect it. They did it on the first day of their 100th Test match at the P Sara Oval in Colombo after a 259-run thrashing less than a week ago in Galle, and they did it in even more spectacular fashion on the third day yesterday.\r\n\r\nIt was apt that the player who exemplifies the aforementioned qualities, Shakib Al Hasan, was one of the main actors in Bangladesh revival with his fifth Test century.\r\n\r\nAfter ending the second day with a spell of play that produced three wickets for six runs in seven balls, followed by batting from Shakib that could only be described as reckless as Bangladesh went to the close 124 runs behind and with five wickets in hand, the visitors ended the third day with a lead of 75, although Sri Lanka finished without loss with 52 runs on the board in 13 overs.\r\n\r\nThere was time enough for Dimuth Karunaratne to be dropped by skipper Mushfiqur Rahim off Subashis Roy off a difficult chance down the leg side, but it could not take much of the gloss off a wearing pitch and their position in the match.\r\n\r\nBefore that, Shakib century and a 75 on debut from Mosaddek Hossain carried Bangladesh to 467, a first-innings lead of 129, before Mosaddek wild heave missed the mark and he was stumped to become Sri Lanka skipper Rangana Herath 1,001st first-class wicket in the 135th over. Herath earlier became the 12th bowler from the subcontinent to reach the 1,000 first-class wicket landmark by getting Mustafizur Rahman leg-before in the 129th over.'),
(17, 'Tigers close in on rare away victory', '2017-03-20 02:12:23', 'Saymatul Tuba', 'shakib_73.jpg', 'Bangladesh are a few steps away from creating history in their 100th Test match. That may be a tempting way to see the situation that currently prevails in Colombo before Bangladesh attempt to take the two Sri Lankan wickets as early as possible today and minimise the hosts lead which currently stands at 139 in order to walk away with a share of the spoils in the two-match series, but if they manage to pull it off today, the enormity of the achievement may even exceed the significance of the 100th Test.\r\n\r\nFrom the debacle of the 259-run loss in the first Test, which in turn led to selection confusion, which then led to interference from every quarter that resulted in a profoundly divided touring party before this current Test, Bangladesh are on the cusp of eyeing a Test win against a team they have never beaten before and on a ground which has produced only innings-defeats for them in the past.'),
(18, 'This win started when we lost in Galle: Tamim Iqbal', '2017-03-20 02:12:23', 'kowshik das', 'tam_1.jpg', 'Tamim Iqbal, the man-of-the-match in Bangladeshâ€™s historic four-wicket win in the second Test match against Sri Lanka today, said the 259-run defeat in the first Test in Galle worked as an impetus for their win in Colombo.\r\n\r\nâ€œI think this win started when we lost the match in Galle,â€ Tamim elucidated when he spoke after the match.\r\n\r\nâ€œWe had a long chat with the coach, and the players stepped up. The way the bowlers bowled in the first innings was quite exceptional,â€ said Tamim, who scored a crucial 82-run knock in the second innings to lay the platform for victory.\r\n\r\nâ€œThat changed the whole thing. When you are chasing this kind of total, you have to be a little aggressive. Me and Sabbir were talking in the middle to look for runs. All came good except the last shot. The coach has backed us a lot. We are very lucky to have him,â€ the Bangladesh left-handed opener added.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`Id`);

--
-- Indexes for table `entertainment`
--
ALTER TABLE `entertainment`
  ADD PRIMARY KEY (`Id`);

--
-- Indexes for table `international`
--
ALTER TABLE `international`
  ADD PRIMARY KEY (`Id`);

--
-- Indexes for table `national`
--
ALTER TABLE `national`
  ADD PRIMARY KEY (`Id`);

--
-- Indexes for table `sports`
--
ALTER TABLE `sports`
  ADD PRIMARY KEY (`Id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin`
--
ALTER TABLE `admin`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;
--
-- AUTO_INCREMENT for table `entertainment`
--
ALTER TABLE `entertainment`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=20;
--
-- AUTO_INCREMENT for table `international`
--
ALTER TABLE `international`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;
--
-- AUTO_INCREMENT for table `national`
--
ALTER TABLE `national`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;
--
-- AUTO_INCREMENT for table `sports`
--
ALTER TABLE `sports`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
